Port $DEFAULT_SSH_PORT
HostKey /etc/ssh/ssh_host_ecdsa_key
Ciphers aes128-cbc,aes192-cbc,aes256-cbc,aes128-gcm@openssh.com,aes256-gcm@openssh.com
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 2
VersionAddendum ''
Banner none
Match User $WANPAD_USERNAME
    PubkeyAuthentication yes
    MaxSessions 100
